defaults: &defaults
  working_directory: /root/unexpected-immutable
  docker:
      - image: node:boron-slim

version: 2
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - persist_to_workspace:
          root: /root
          path:
            - unexpected-immutable
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root
      - deploy:
          name: NPM login
          command: echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
      - deploy:
          name: build
          command: npm run build
      - deploy:
          name: Publish
          command: ls -all . && cat .npmignore

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
