defaults: &defaults
  working_directory: ~/unexpected-immutable
  docker:
      - image: node:dubnium

version: 2
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: v1-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      - run: npm test

workflows:
  version: 2
  build_test:
    jobs:
      - build_and_test
